apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  annotations: 
    kubernetes.io/ingress.class: nginx
  name: ingress
  namespace: default
spec: 
  rules: 
    - host: guestbook.local
      http: 
        paths: 
          - 
            backend: 
              serviceName: helm-guestbook
              servicePort: http
            path: /guestbook
